### PR TITLE
Fix issue #75 // flux rss réinitialisé à chaque commit

### PR DESCRIPTION
**Pull request by G4dter**
C'est largement factorisable mais c'est un premier jet.
Par contre, la création de pages statiques ne fonctionnent pas.
Mais je ne sais pas si le script le permettait initialement, je ne vois aucune référence au fichier "static" dans le programme translate_and_export_and_zip.sh

### CODE REVIEW

**Comment by c-geek** [comment]
If you don't mind, I will wait before including it. I would like to have automated tests that I would include in Travis.

About static pages: a static page is nothing but an article to which we set the "static" property. So your code seems all good :+1:

**Comment by G4dter** [comment]
Not a problem at all.
Ok, i understand the "static" treatment. 
One property will miss when we treat static page. The "page" property should be set to true at this moment.

**Comment by c-geek** [comment]
I don't get it, what will we miss?

**Comment by G4dter** [comment]
When a new static page will be created, the property "page": true will not be set.
It has to be done in the meta/static.txt loop.

**Comment by c-geek** [comment]
Yes exactly! I thought we had a difficulty here :stuck_out_tongue:

**Comment by c-geek** [comment]
Ça roxxe !

**Pull request merged**
